### ISSUE TITLE
Summarize

### ISSUE THREAD

**Issue by grztofdev** [shrivastavadisha/repo_level_prompt_generation#1]
Hi,
I am a little bit confused, what is the goal of this repo?
What I understand is that it takes the whole repository, chunks it into small* pieces, and then based on a prompt given by the user generates the response?
That is how almost all langchain application works, so what is the difference between yours?

I suppose that chunking the codebase into smaller parts* is a little bit more complicated than in normal langchain apps and you have created special algorithms that create a kind of map of all classes, functions, imports, etc, and based on this map, context is made and sent into chatgpt. Am I right?

Thanks in advance!

**Comment by shrivastavadisha** [comment]
Hi,
This repository contains implementation and trained checkpoints for our work [Repository-Level Prompt Generation for Large Language Models of Code](https://arxiv.org/abs/2206.12839). 

The prompt is not given by the user. The RLPG framework automatically selects a relevant context from the repository conditioned on the intended completion. RLPG is specifically trained to do so such that the inclusion of that relevant context leads to an accurate prediction. Besides the framework, we also show the benefits of using prompt proposals ( which determine where from and what to take from the repository). We compare RLPG that uses prompt proposals with several retrieval baselines and the improvements are significant. We use Codex as the base LLM in our experiments but the framework will work with any LLM. You need to have just API access and no access to the weights are needed.

Hope this clarifies your doubt. I will suggest reading the paper for more details!
