### ISSUE TITLE
Does this code repository include the code for the **Prompt Composer** module?

### ISSUE THREAD

**Issue by zhang-ge-hao** [shrivastavadisha/repo_level_prompt_generation#2]
Thank you for your excellent work. I believe that it is very valuable and I hope to reproduce some results from the paper, including RLPG-H/R and RLPG-BM25. However, after reviewing the readme.md, it seems that the code repository only contains training and validation code for the Prompt Proposal Classifier. Is the code for the Prompt Composer module included in this code repository? Is there an open-source implementation of this module available for access?

**Comment by HIT-five** [comment]
No Prompt Composer module in this repo

**Comment by shrivastavadisha** [comment]
Sorry for the late response! The Prompt Composer is simply the concatenation of the context from the predicted prompt proposal and context around the target hole.

**Comment by shrivastavadisha** [comment]
Sorry for the late response! The Prompt Composer is simply the concatenation of the context from the predicted prompt proposal and context around the target hole.
